#####################################
# 具体配置 可以参考
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
#####################################
# banner
banner:
  charset: UTF-8
  location: classpath:banner.txt

# 应用属性配置
application:
  name: schedule-job
  version: v1.0.0

# 服务端配置
server:
  port: 54321
  address: 127.0.0.1
  contextPath: /
  compression:
    enabled: true

# WARNING: `spring.config.name` and `spring.config.location` are used very early to
# determine which files have to be loaded so they have to be defined as an environment
# property (typically OS env, system property or command line argument).
spring:
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
    converters:
      preferred-json-mapper: true
  mvc:
    favicon:
      enabled: false
  datasource:
      druid:
        url: jdbc:mysql://127.0.0.1:3306/schedule_job?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&allowMultiQueries=true
        username: root
        password: QWER!@#123
        driver-class-name: com.mysql.jdbc.Driver


# multipart 配置
multipart:
  enabled: true
  file-size-threshold: 0
  location: /
  max-file-size: 1Mb
  max-request-size: 10Mb

# MyBatis
mybatis:
  mapperLocations: classpath:/mapper/**/*Mapper.xml
  configLocation: classpath:mybatis-config.xml

# logback config
# You cannot use extensions in the standard logback.xml configuration file since it’s loaded too early.
# You need to either use logback-spring.xml or define a logging.config property.
# path不以'/'开头时，默认是从此类所在的包下取资源；
# path以'/'开头时，则是从项目的ClassPath根下获取资源。在这里'/'表示ClassPath
# Class.getResource和ClassLoader.getResource的区别
logging:
  config: classpath:config/logback.xml

# 配置文件名称，内部加载使用
config:
  quartz-file-name: quartz.properties
  redis-file-name: redis-prod.yml
#  db-file-name: datasource.yml
